package application.exceptions

class UserAlreadyExists : Exception()
